---
# Usage: http://ruhoh.com/usage/configure/

RuhohSpec: '1.0'
theme : div
production_url: http://div.github.com/blog/

posts:
  permalink: /:categories/:title/
  summary_lines: 2000
  latest: 10

pages:
  permalink: 'pretty'

base_path: '/blog'