title : Random thoughts by Igor Davydov
tagline: Blog Tagline
author :
  name : Igor Davydov
  email : igor@divrb.com
  github : div
  twitter : divrb
  feedburner : feedname

navigation :
  # - archive.html
  # - tags.html
  # - categories.html
  # - pages.html
  - about.md

